=== SavaDtrv/XML/XML files/CheckedByThePolice.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<schema xmlns = "http://www.w3.org/2001/XMLSchema"
        xmlns:mynspc = "http://example.com/XMLProject"
        elementFormDefault = "qualified"
        targetNamespace = "http://example.com/XMLProject"
>

    <complexType name="People">
        <sequence>
            <element name = "person" type = "mynspc:Person" minOccurs = "0" maxOccurs = "unbounded" />
        </sequence>
    </complexType>

    <complexType name = "Person">
        <attributeGroup ref = "mynspc:ID_data" />

        <sequence>
            <group ref = "mynspc:Personal_data" />
        </sequence>
    </complexType>

    <complexType name="Criminal_acts">
        <attribute name="isCriminal" type="boolean" />

        <sequence>
            <element name="acts" type="string" />
        </sequence>
    </complexType>

    <complexType name = "Times_checked"> <!-- By the police -->
        <sequence>
            <element name = "times" type = "integer" minOccurs="0" />
            <element name = "this_month" type = "boolean" minOccurs="0" />
        </sequence>
    </complexType>

    <complexType name="Additional_person_info">
        <sequence>
            <element name = "phone" type = "string" minOccurs = "0" maxOccurs = "2" />
            <element name = "email" type = "mynspc:Email" minOccurs = "0" maxOccurs = "2" />
        </sequence>
    </complexType>

    <simpleType name = "Email">
        <restriction base = "string">
            <pattern value = ".+@.+" />
        </restriction>
    </simpleType>

    <attributeGroup name = "ID_data">
        <attribute name = "id_number" type = "string" use = "required" />
        <attribute name = "id_date_of_issue" type = "date" use = "required" />
        <attribute name = "id_expiry" type = "date" use = "required" />
        <attribute name = "id_issued_by" type = "string" use = "required" />
        <attribute name = "signature" type = "boolean" use = "required" />
    </attributeGroup>

    <group name = "Personal_data">
        <sequence>
            <!-- Data by ID -->
            <element name = "first_name" type = "string" />
            <element name = "fathers_name" type = "string" minOccurs="0" />
            <element name = "surname" type = "string" />
            <element name = "personal_NO" type = "string" />
            <element name = "sex" type = "string" minOccurs="0" />
            <element name = "eyes_color" type = "string" minOccurs="0" />
            <element name = "height" type = "integer" minOccurs="0" />
            <element name = "date_of_birth" type = "date" />
            <element name = "nationality" type = "string" />
            <element name = "place_of_birth" type = "string" />
            <element name = "residence" type = "string" />
            <!-- Additional info for the person -->
            <element name="more_person_info" type="mynspc:Additional_person_info" minOccurs="0" />
            <!-- Person to contact if something happened to you -->
            <element name="close_person" type="mynspc:Additional_person_info" minOccurs="0" />
            <!-- Times checked by the police this month -->
            <element name = "times_checked" type = "mynspc:Times_checked" />

            <element name = "criminal_acts" type = "mynspc:Criminal_acts" minOccurs="0" />
        </sequence>
    </group>

    <element name="people" type="mynspc:People" />
</schema>

=== SavaDtrv/XML/XML files/CheckedByThePolice_1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<people xmlns="http://example.com/XMLProject"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://example.com/XMLProject CheckedByThePolice.xsd">

       <person id_number="682593234" id_date_of_issue="2008-12-15"
               id_expiry="2018-12-15" id_issued_by="МВР Пловдив" signature="true">
           <first_name>Петър</first_name>
           <fathers_name>Георгиев</fathers_name>
           <surname>Петров</surname>
           <personal_NO>9011246532</personal_NO>
           <sex>Мъж</sex>
           <eyes_color>Кафяви</eyes_color>
           <height>178</height>
           <date_of_birth>1990-11-24</date_of_birth>
           <nationality>България</nationality>
           <place_of_birth>Пловдив</place_of_birth>
           <residence>Пловдив</residence>
           <more_person_info>
               <phone>0892322265</phone>
               <email>petar-petrov@gmail.com</email>
           </more_person_info>
           <close_person>
               <phone>0892323266</phone>
               <email>petar@gmail.com</email>
           </close_person>
           <times_checked>
               <times>4</times>
               <this_month>true</this_month>
           </times_checked>
           <criminal_acts isCriminal="false"></criminal_acts>
       </person>

       <person id_number="682593235" id_date_of_issue="2012-10-15"
               id_expiry="2022-10-15" id_issued_by="МВР Стара Загора" signature="true">
           <first_name>Мира</first_name>
           <fathers_name>Георгиева</fathers_name>
           <surname>Ангелива</surname>
           <personal_NO>9409106533</personal_NO>
           <sex>Жена</sex>
           <eyes_color>Сини</eyes_color>
           <height>165</height>
           <date_of_birth>1994-09-10</date_of_birth>
           <nationality>България</nationality>
           <place_of_birth>Стара Загора</place_of_birth>
           <residence>София</residence>
           <more_person_info>
               <phone>0892566511</phone>
               <email>mira_angelova@gmail.com</email>
           </more_person_info>
           <close_person>
               <phone>0892566423</phone>
               <email>mira@gmail.com</email>
           </close_person>
           <times_checked>
               <times>2</times>
               <this_month>true</this_month>
           </times_checked>
           <criminal_acts isCriminal="false"></criminal_acts>
       </person>
</people>

=== SavaDtrv/XML/XML files/CheckedByThePolice_4.xml
<?xml version="1.0" encoding="UTF-8" ?>
<people xmlns="http://example.com/XMLProject"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://example.com/XMLProject CheckedByThePolice.xsd">

    <person id_number="682593239" id_date_of_issue="2016-08-26"
            id_expiry="2026-08-26" id_issued_by="МВР Стара Загора" signature="true">
        <first_name>Мирослава</first_name>
        <fathers_name>Радославова</fathers_name>
        <surname>Петрова</surname>
        <personal_NO>8807156533</personal_NO>
        <sex>Жена</sex>
        <date_of_birth>1988-07-15</date_of_birth>
        <nationality>България</nationality>
        <place_of_birth>Стара Загора</place_of_birth>
        <residence>София</residence>
        <more_person_info>
            <email>mira.8807@abv.com</email>
        </more_person_info>
        <close_person>
            <phone>0898562314</phone>
        </close_person>
        <times_checked>
            <times>0</times>
            <this_month>false</this_month>
        </times_checked>
        <criminal_acts isCriminal="true" />
    </person>
</people>

=== SavaDtrv/XML/XML files/CheckedByThePolice_2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<people xmlns="http://example.com/XMLProject"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://example.com/XMLProject CheckedByThePolice.xsd">

    <person id_number="682593236" id_date_of_issue="2018-07-05"
            id_expiry="2028-07-05" id_issued_by="МВР Стара Загора" signature="true">
        <first_name>Красимир</first_name>
        <fathers_name>Радомиров</fathers_name>
        <surname>Димитров</surname>
        <personal_NO>0006036533</personal_NO>
        <sex>Мъж</sex>
        <eyes_color>Зелени</eyes_color>
        <height>180</height>
        <date_of_birth>2000-06-03</date_of_birth>
        <nationality>България</nationality>
        <place_of_birth>Ямбол</place_of_birth>
        <residence>Пловдив</residence>
        <more_person_info>
            <phone>0892633311</phone>
            <email>kras.dimitrov@gmail.com</email>
        </more_person_info>
        <close_person>
            <phone>0892565656</phone>
            <email>krasi@gmail.com</email>
        </close_person>
        <times_checked>
            <times>0</times>
            <this_month>false</this_month>
        </times_checked>
        <criminal_acts isCriminal="false"></criminal_acts>
    </person>

    <person id_number="682593237" id_date_of_issue="2013-07-25"
            id_expiry="2023-07-05" id_issued_by="МВР Пловдив" signature="true">
        <first_name>Георги</first_name>
        <fathers_name>Радомиров</fathers_name>
        <surname>Димитров</surname>
        <personal_NO>8506036533</personal_NO>
        <sex>Мъж</sex>
        <eyes_color>Кафяви</eyes_color>
        <height>175</height>
        <date_of_birth>1985-06-03</date_of_birth>
        <nationality>България</nationality>
        <place_of_birth>Пловдив</place_of_birth>
        <residence>София</residence>
        <more_person_info>
            <phone>0895869633</phone>
        </more_person_info>
        <close_person></close_person>
        <times_checked>
            <times>8</times>
            <this_month>true</this_month>
        </times_checked>
        <criminal_acts isCriminal="true">
            <acts>
                Притежание на повече от половин грам канабис;
                Дребни кражби, в продължение на дълго време;
            </acts>
        </criminal_acts>
    </person>
</people>

=== SavaDtrv/XML/XML files/CheckedByThePolice_3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<people xmlns="http://example.com/XMLProject"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://example.com/XMLProject CheckedByThePolice.xsd">

    <person id_number="682593238" id_date_of_issue="2016-08-25"
            id_expiry="2026-08-25" id_issued_by="МВР Стара Загора" signature="true">
        <first_name>Мирослава</first_name>
        <fathers_name>Радославова</fathers_name>
        <surname>Петрова</surname>
        <personal_NO>8807156533</personal_NO>
        <sex>Жена</sex>
        <eyes_color>Пъстри</eyes_color>
        <height>170</height>
        <date_of_birth>1988-07-15</date_of_birth>
        <nationality>България</nationality>
        <place_of_birth>Стара Загора</place_of_birth>
        <residence>София</residence>
        <more_person_info>
            <email>mira.8807@abv.com</email>
        </more_person_info>
        <close_person>
            <phone>0898562314</phone>
            <email>parent@abv.com</email>
        </close_person>
        <times_checked>
            <times>0</times>
            <this_month>false</this_month>
        </times_checked>
        <criminal_acts isCriminal="true">
            <acts>
                Липса(изгубени/забравени) на документи за самоличност, в следствие на което оказва съпротива при задържане;
            </acts>
        </criminal_acts>
    </person>
</people>

=== SavaDtrv/XML/XML files/CheckedByThePolice_5.xml
<?xml version="1.0" encoding="UTF-8" ?>
<people xmlns="http://example.com/XMLProject"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://example.com/XMLProject CheckedByThePolice.xsd">

    <person id_number="682593238" id_date_of_issue="2016-08-25"
            id_expiry="2026-08-25" id_issued_by="МВР Стара Загора" signature="true">
        <first_name>Иван</first_name>
        <surname>Петров</surname>
        <personal_NO>8807156534</personal_NO>
        <date_of_birth>1988-07-15</date_of_birth>
        <more_person_info>
            <phone>0895624173</phone>
        </more_person_info>
        <close_person>
            <phone>0898562314</phone>
        </close_person>
        <criminal_acts isCriminal="false" />
    </person>

    <person id_number="682593239" id_date_of_issue="2016-08-27" id_expiry="2026-08-27" id_issued_by="МВР Варна" signature="true">
        <first_name>Пенко</first_name>
        <surname>Станков</surname>
        <personal_NO>8807156535</personal_NO>
        <sex>Мъж</sex>
        <eyes_color>Сини</eyes_color>
        <height>175</height>
        <date_of_birth>1988-07-16</date_of_birth>
        <nationality>България</nationality>
        <residence>София</residence>
        <times_checked>
            <times>5</times>
            <this_month>true</this_month>
        </times_checked>
    </person>
</people>
